// Generated by https://quicktype.io

export interface BannerApiType {
    success:     boolean;
    social_info: Banner[];
}

export interface Banner {
    id:          number;
    name:        string;
    type:        string;
    icon:        string;
    redirect_url:         string;
    text_url?: string;
    active:      boolean;
    cover_photo: string;
    cover_photo_url?: string;
    meta?: string;
    updated_at:  string;
    created_at:  string;

}
