// Generated by https://quicktype.io

export interface BannerApiType {
    success:     boolean;
    social_info: Banner[];
}

export interface Banner {
    name:        string;
    type:        string;
    icon:        string;
    url:         string;
    cover_photo: string;
    cover_photo_url?: string;
    meta?: string;
    updated_at:  string;
    created_at:  string;
    id:          number;
}
